<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="7" total="8" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-05T18:49:44 IST" name="Default suite" finished-at="2024-02-05T18:50:30 IST" duration-ms="46499">
    <groups>
    </groups>
    <test started-at="2024-02-05T18:49:44 IST" name="Default test" finished-at="2024-02-05T18:50:30 IST" duration-ms="46499">
      <class name="features.contactInsights.AddNewContactFeature">
        <test-method is-config="true" signature="launchWebsite()[pri:0, instance:features.contactInsights.AddNewContactFeature@235ecd9f]" started-at="2024-02-05T18:49:44 IST" name="launchWebsite" finished-at="2024-02-05T18:49:45 IST" duration-ms="1846" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchWebsite -->
        <test-method signature="theUserCannotCreateANewContactWithInvalidEmail()[pri:0, instance:features.contactInsights.AddNewContactFeature@235ecd9f]" started-at="2024-02-05T18:49:46 IST" name="theUserCannotCreateANewContactWithInvalidEmail" description="@ALW-12623 @TR-12623 @Regression
	  @BugALW-23622
	  Scenario: The user can&#039;t create a new contact with invalid email" finished-at="2024-02-05T18:50:30 IST" duration-ms="44607" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The Save Button is enabled expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The Save Button is enabled expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at helpers.Assertions.expectToBeDisabled(Assertions.java:42)
at steps.contactInsights.CreateContactDialogSteps.thenTheSaveButtonIsDisabledInTheCreateContactDialog(CreateContactDialogSteps.java:181)
at features.contactInsights.AddNewContactFeature.theUserCannotCreateANewContactWithInvalidEmail(AddNewContactFeature.java:485)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- theUserCannotCreateANewContactWithInvalidEmail -->
      </class> <!-- features.contactInsights.AddNewContactFeature -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
